POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InhpYW9sb25neWFAcXEuY29tIiwiZXhwIjoxNzc2MzQxNzI4LCJ1c2VySWQiOjB9.arFoJw0nHKqi4_iI7tDJHiVRD2CYYVvMN9ak9CVPiGI

{
    "name": "Test Event!!!",
    "description": "This is the second test event.",
    "location": "Test Location",
    "datetime": "2024-07-01T18:00:00Z"
}