POST http://localhost:8080/events
content-type: application/json

{
    "name": "Test Event2",
    "description": "This is the second test event.",
    "location": "Test Location",
    "datetime": "2024-07-01T18:00:00Z"
}